### PR TITLE
Replace direct equality with InventoryUtil.areItemsEqual

### LINKED ISSUE #340: turtle.suck() and turtle.drop() give incorrect return values when an inventory is full
turtle.drop(), turtle.dropUp(), turtle.dropDown(), turtle.suck(), turtle.suckDown(), and turtle.suckUp() will sometimes give incorrect return values when putting items into an inventory.

- Inserting X into an item full of Y will result in "false, No space for items" (Expected)
- Inserting X into an item full of X will result in "true" (Unexpected) (No items were moved)

This appears to be the same for both turtle.suck() and turtle.drop().

### PR DESCRIPTION
**Pull request by SquidDev**
Some IItemHandler.insertItem implementations clone the item, so we must
check whether the object is equal instead. It would be possible to
compare stack sizes instead, I just feel this is a little clearer.

Fixes #340

### CODE REVIEW

**Comment by dan200** [comment]
Could we do this check inside InventoryUtils.storeItems instead of every bit of calling code? I like the convention of returning the same ItemStack object to indicate no change

**Comment by SquidDev** [comment]
Updated. Yeah, this was a little neater :).

File: src/main/java/dan200/computercraft/shared/util/InventoryUtil.java [hunk 1]
```diff
@@ -169,7 +169,7 @@ private static ItemStack storeItems( ItemStack stack, IItemHandler inventory, in
             if( remainder == null ) break;
             remainder = inventory.insertItem( slot, remainder, false );
         }
-        return remainder;
+        return areItemsEqual( stack, remainder ) ? stack : remainder;
```
Comment (dan200) [inline src/main/java/dan200/computercraft/shared/util/InventoryUtil.java]: for extra safety, line 166 could be "remainder = stack.copy()", incase the code modifies the itemstack in-place

Comment (SquidDev) [inline src/main/java/dan200/computercraft/shared/util/InventoryUtil.java]: Hrrmrm, that does violate the contract of `insertMethod` (the docs say not to modify the stack), but better safe than sorry I guess :).

Comment (SquidDev) [inline src/main/java/dan200/computercraft/shared/util/InventoryUtil.java]: Done!
